version: "3.9"
# base compose. utilizes overrides
# dev: docker-compose up. deployment: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up
services:
  web:
    env_file:
      - .env
    user: app_runner
    build: .
    image: fuelgh_app
    command: sh -c "python fuelgh/manage.py collectstatic --no-input && python fuelgh/manage.py migrate && uwsgi --ini uwsgi.ini --socket :${SERVICE_PORT}"
    ports:
      - 18001:18001
    depends_on:
      - db
      - redis
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  redis:
    image: redis
    command: redis-server
  celery_worker:
    env_file:
      - .env
    user: app_runner
    image: fuelgh_app
    working_dir: /home/app_runner/code/fuelgh
    command: celery -A fuelapp worker -l info
    depends_on:
      - redis
      - web
  celery_beat:
    env_file:
      - .env
    user: app_runner
    image: fuelgh_app
    working_dir: /home/app_runner/code/fuelgh
    command: celery -A fuelapp beat -l debug
    depends_on:
      - redis
      - web
