version: "3.9"

services:
  nginx:
    env_file:
      - .env
    image: nginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./fuelgh/static/:/etc/nginx/static/
    ports:
      - 80:80
  web:
    env_file:
      - .env
    user: app_runner
    build: .
    working_dir: /home/app_runner/code/fuelgh/
    command: python manage.py test
    ports:
      - 18001:18001
    depends_on:
      - db
      - redis
  db:
    env_file:
      - .env
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8081:8080
  redis:
    image: redis
    command: redis-server
  celery_worker:
    env_file:
      - .env
    user: app_runner
    build:
      context: .
    working_dir: /home/app_runner/code/fuelgh
    command: celery -A fuelapp worker -l info
    depends_on:
      - redis
      - web
