# Generated by Django 3.1.6 on 2021-02-20 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelprices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='omc',
            name='owner',
        ),
    ]
