# Generated by Django 3.1.6 on 2021-02-09 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Omc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=20)),
                ('diesel_price', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('petrol_price', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Omcs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('describer_string', models.CharField(default='', max_length=50)),
                ('region', models.CharField(default='', max_length=50)),
                ('locality', models.CharField(default='', max_length=50)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=25)),
                ('omc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelprices.omc')),
                ('uploader', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='FuelStation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
