# Generated by Django 3.1.6 on 2021-04-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelprices', '0002_remove_omc_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelstation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='omc',
            options={},
        ),
        migrations.AlterField(
            model_name='omc',
            name='diesel_price',
            field=models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='omc',
            name='petrol_price',
            field=models.DecimalField(db_index=True, decimal_places=3, default=0, max_digits=5),
        ),
    ]
