# Generated by Django 3.1.6 on 2021-04-04 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuelprices', '0003_auto_20210404_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='omc',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='omc',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=20),
        ),
    ]
