# Generated by Django 3.1.6 on 2021-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelprices', '0004_auto_20210404_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.CharField(db_index=True, max_length=36)),
                ('excel_file', models.FileField(upload_to='')),
            ],
        ),
    ]
